apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: u463y2sla-java-springboot
  janus-idp.io/tekton: u463y2sla-java-springboot
  backstage.io/kubernetes-id: u463y2sla-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u463y2sla-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
